apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-resources
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "10"
    limits.memory: 20Gi
    requests.storage: 500Gi
    pods: "50"
    services: "100"
    services.loadbalancers: "2"
    services.nodeports: "20"
    persistentvolumeclaims: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limit-range
spec:
  limits:
  - default:
      cpu: 1
      memory: 1024Mi
    defaultRequest:
      cpu: 0.5
      memory: 256Mi
    type: Container