apiVersion: v1
kind: ResourceQuota
metadata:
  name: pro-resources
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 10Gi
    limits.cpu: "30"
    limits.memory: 200Gi
    requests.storage: 1000Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: pro-limit-range
spec:
  limits:
  - default:
      cpu: 1
      memory: 1024Mi
    defaultRequest:
      cpu: 0.5
      memory: 256Mi
    type: Container